### ISSUE TITLE
What is needed for Rollup support?

### ISSUE THREAD

**Issue by benmccann** [rixo/sapper-template-hot#3]
> Only available for Webpack currently. (Rollup support for Sapper is pretty hard, and not very high on my priority list.)

I'm curious, is there anything that makes Rollup support harder than Webpack support?

**Comment by rixo** [comment]
Hi Ben! Sorry for letting this wait for so long...

In fact, what makes Rollup support harder is that Webpack support was easy. I think when I wrote the quoted line Rollup HMR was barely a thing.

If I remember correctly, all I've had to do to get HMR support working with Webpack had basically been to replace `svelte-loader` with my `svelte-loader-hot` and add Webpack's HotModuleReplacementPlugin. I didn't dig into Sapper's own code at all at the time, just forged ahead with my Sapper Webpack HMR project, and didn't really encounter HMR limitations that I would have noticed.

On the other hand, to begin to have some working Rollup HMR, I did have to dig. To make it work, I've had to disable [Sapper's "dev client"](https://github.com/sveltejs/sapper/blob/master/sapper-dev-client.js) (from a Rollup plugin, see [here](https://github.com/rixo/rollup-plugin-svelte-hot/blob/24f8a8fb71dfe863d476721959e1730a5e515a26/hmr/index.js#L52) -- something's telling me this is not where this should live...).

In the end, it was not _so_ terrible to get support with `rollup-plugin-hot`, because this plugin is happy to ride over another server and only deal with HMR updates. But still, it would need quite involved modifications in Sapper's codebase itself to be done properly. And as you have seen in the discussion / experimentation around HMR with Nollup, integration of a "mostly Rollup compatible" can be way harder. Not because the "Rollup compatible" part would be lacking, but because Nollup also wants to be the dev server, and this clashes hard with Sapper's own working...

I've heard some progress have been made in the direction of making Sapper more modular, specifically to solve this kind of issues. I was thinking you've been involved in this, even. Also, I've been discussing with @antony to move Sapper + Nollup forward -- which I'd love to do, because now that I've seen it work with Nollup, I'm a bit meh at the speed you get with just Rollup during development...

But unfortunately, I've had a very thin OSS bandwidth since all those developments happened, and haven't really had any time to come back at it :-/ Rather been growing my list of "things to catch up" in this regard, lately...

Cheers!

**Comment by benmccann** [comment]
So if we got it easier to integrate Nollup would that be basically what's needed for `rollup-plugin-hot`?

Yeah, I have been working towards making Sapper more modular. Mostly I've been focused on trying to remove the `sapper-internal` Rollup plugin that does css handling. Rich lent a hand this weekend and really moved that forward. The CSS handling was woven throughout the codebase, but I just sent a PR a few minutes ago that finishes getting it mostly into the `sapper-internal` rollup plugin. It should be much easier to extract that plugin out into an external plugin now and remove it from Sapper so that the Rollup build isn't doing anything special that the webpack build isn't doing

**Comment by rixo** [comment]
I think fixing `rollup-plugin-hot` might be trivial, as opposed to what's needed for Nollup.

It's already been working for a while [apparently](https://github.com/rixo/sapper-template-hot/issues/4). I've also had such a feedback quite some time ago.

I've just spent a few minutes trying to run it myself, but no luck... I know I've seen it working already, but I've never really used it myself so I can't tell what could have been subtly broken or missing.

**Comment by rixo** [comment]
Well, I guess better solutions to this problem have now arisen :)
